version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-iot
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - mysql_iot:/var/lib/mysql

volumes:
  mysql_iot: